In [1]:
import numpy as np

# [ND-array](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/IntroducingTheNDarray.html)
* Main fature of numpy
* Advantageous:
 1. Multiple dimensions
 2. Fast
* Homogeneous

In [2]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
x = x.reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# by columns
x * np.array([0., 1., 2.])

array([[  0.,   1.,   4.],
       [  0.,   4.,  10.],
       [  0.,   7.,  16.]])

In [5]:
# slicing
x[:2][:3]

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
# complex indexing
x[x % 2 == 0] *= -1
x

array([[ 0,  1, -2],
       [ 3, -4,  5],
       [-6,  7, -8]])

# 1. [Access](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/AccessingDataAlongMultipleDimensions.html)
* Like sequences, but EACH dimension
* ~~arr[z][y][x]~~ --> arr[z, y, x]
* arr[0] = arr[0, :, :]
* Most RECENT dimension is axis 0

In [7]:
x = np.array([[[1, 2, 3],
               [4, 5, 6]],
              
              [[7, 8, 9],
               [0, 1, 2]]])
x[1, 0, 2]

9

# 2. [Manipulation](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/AccessingDataAlongMultipleDimensions.html#Manipulating-Arrays)
* Methods DO NOT make a copy
 * Create new object with same references

In [8]:
#x = x.reshape(3, 4)
x.shape = (3, 4)
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [9]:
x = x.transpose()
x

array([[1, 5, 9],
       [2, 6, 0],
       [3, 7, 1],
       [4, 8, 2]])

In [10]:
x.reshape(2, -1)

array([[1, 5, 9, 2, 6, 0],
       [3, 7, 1, 4, 8, 2]])

# 3. [Attributes](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/BasicArrayAttributes.html)

In [11]:
x.ndim

2

In [12]:
x.shape

(4, 3)

In [13]:
x.dtype

dtype('int32')

# 4. [Creating ND-arrays](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/FunctionsForCreatingNumpyArrays.html)
* From existing
* Fixed
* Random

In [14]:
# from a sequence
np.array([i for i in range(5)])

array([0, 1, 2, 3, 4])

In [15]:
# supports nesting
np.array([[1, 2, 3], [4, 5, 6]]).shape

(2, 3)

In [16]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(5, 15, 5)

array([  5. ,   7.5,  10. ,  12.5,  15. ])

In [19]:
# normal distribution
# mean-1 std-dev-5
np.random.normal(1, 5, 3)

array([ 0.26797685,  3.88318229,  2.92562605])

In [20]:
# specific type
np.array([1.1, 1.7, 2.5], dtype=int)

array([1, 1, 2])

In [21]:
# concatenation
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])

In [22]:
np.vstack([x, y])

array([[ 1,  2,  3],
       [-1, -2, -3]])

In [23]:
np.hstack([x, y])

array([ 1,  2,  3, -1, -2, -3])

# 5. [Iterating](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/ArrayTraversal.html)
* Several valid ways
* Row-major is default

In [24]:
# row-major (C ordering)
# last axis first
x = np.array([[25, 6], [9, -40]])
[i for i in np.ndenumerate(x)]

[((0, 0), 25), ((0, 1), 6), ((1, 0), 9), ((1, 1), -40)]

In [25]:
# column-major (F ordering)
# 0th axis first
it = np.nditer(x, flags=['multi_index'], order='F')
while not it.finished:
    print(it.multi_index, it[0])
    it.iternext()

(0, 0) 25
(1, 0) 9
(0, 1) 6
(1, 1) -40


### Other methods
* nditer
* ndindex
* flatiter
* lib.Arrayterator

# 6. ["Vectorized" operations](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html)
* Vectorization: use of pre-compiled low-level language code
* Homogenuity required for vectorization -> speedup
* ALL of the following use vectorization

### Unary
* $f(x)$
* Sqrt, sin, log, etc.

In [26]:
# based on scalars
# applied elementwise
x = np.arange(9).reshape(3, 3)
x + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Binary
* $f(x, y)$
* Add, multiply, etc.

In [27]:
y = np.arange(9).reshape(3, 3)
# array, array: corresponding elements
x * y

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [28]:
# array, scalar: elementwise
x ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [29]:
# also supports logical operations
x < 5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]], dtype=bool)

### Sequential
* $f(\{x_i\}^{n−1}_{i=0})$
* Sum, mean, variance, etc.

In [30]:
# like 1-d sequence
np.sum(x)

36

In [31]:
# overriden with 'axis'
np.sum(x, axis=0)

array([ 9, 12, 15])

In [32]:
np.sum(x, axis=(0,1))

36

# 7. [Array Broadcasting](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html)
* Unequal shapes
* DOES NOT actually create -> saves time and memory
* COMPATIBLE if for each pair of aligned dimensions:
 * Both are same size
 * One is size 1 (causes broadcasting)

In [33]:
# replicates along new dimensions
np.broadcast_to(np.arange(3), (2, 2, 3))

array([[[0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [34]:
x * np.arange(3)

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

In [35]:
# both broadcasted
(np.ndarray((3, 1, 2)) * np.ndarray((3, 1))).shape

(3, 3, 2)

In [36]:
x = np.arange(3)
x[np.newaxis, :, np.newaxis]

array([[[0],
        [1],
        [2]]])

In [37]:
x.reshape(1, 3, 1)

array([[[0],
        [1],
        [2]]])